import { chromium } from "playwright-core"
const BASE = "http://127.0.0.1:5299"
const b = await chromium.launch({ args: ["--no-sandbox"] })
const page = await b.newPage({ viewport: { width: 1280, height: 1000 } })
page.on("console", m => m.type() === "error" && console.log("CONSOLE", m.text().slice(0,160).replace(/\n/g," ")))
page.on("response", r => { if (r.status() >= 400) console.log("HTTP", r.status(), r.url()) })
page.on("pageerror", e => console.log("PAGEERROR", String(e).slice(0,160)))
await page.goto(BASE, { waitUntil: "domcontentloaded" })
await page.waitForSelector(".board-row", { timeout: 30000 })
await page.evaluate(() => ["beanemachine:config","beanemachine:roster","beanemachine:lineup","beanemachine:pool","beanemachine:view"].forEach(k => localStorage.removeItem(k)))
await page.reload({ waitUntil: "domcontentloaded" })
await page.waitForSelector(".board-row", { timeout: 30000 })
const men = await page.$$eval(".board-row", rows => rows.slice(0, 14).map(r => ({
  name: r.querySelector(".who b")?.textContent.trim(),
  code: r.querySelector(".who .code")?.textContent.trim()
})))
await page.click(".decide-cta")
await page.waitForSelector(".trade-team", { timeout: 30000 })
const text = "Fantasy Baseball My Team\nPos\tPlayer\tAction\n" +
  men.map(m => `${m.code}\t${m.name} - ${m.code}\tAdd/Drop`).join("\n")
await page.fill("[data-ctl=paste-roster]", text)
await page.click(".paste-roster button")
await page.waitForSelector(".paste-note", { timeout: 15000 })
console.log("--- PHASE: back to board ---")
await page.locator(".views button", { hasText: "Recommendations" }).first().click()
await page.waitForSelector(".decide", { timeout: 30000 })
await page.waitForTimeout(4000)
console.log("decide-rest count", (await page.$$(".decide-rest")).length, "fine", (await page.$$(".decide-fine")).length)
console.log("MOVES head", (await page.$$eval(".decide-head", n => n.map(e => e.textContent.trim()))))
console.log("--- PHASE: reload ---")
await page.reload({ waitUntil: "domcontentloaded" })
await page.waitForSelector(".board-row", { timeout: 30000 })
await page.waitForTimeout(4000)
console.log("decide-read", await page.textContent(".decide-read").catch(()=>"none"))
console.log("--- PHASE: trade again ---")
await page.locator(".views button", { hasText: /trade/i }).first().click()
await page.waitForSelector(".trade-team", { timeout: 30000 })
console.log("own", (await page.$$eval(".trade-own .who b", n => n.map(e=>e.textContent.trim()))).length)
console.log("unresolved", (await page.$$(".trade-unresolved li")).length)
await b.close()
